### ISSUE TITLE
A question about hidden points removal

### ISSUE THREAD

**Issue by Zscozer** [keeganhk/PointMCD#1]
Hi, I recently read your work "PointMCD: Boosting Deep Point Cloud Encoders via Multi-view Cross-modal Distillation for 3D Shape Recognition" and was very inspired. I still have a question about hidden point removal algorithm: May I ask how your camera viewpoint is designed in the algorithm, because the viewpoint setting [0,0,diameter] (neither xyz nor yaw, pitch, roll form) of the hidden point removal algorithm in open3d does not match the rendered image parameters, and I would like to know if you redesign the camera param inputs. I look forward to your reply, thank you very much.

**Comment by keeganhk** [comment]
Hi, Zscozer. Thanks for your interest in this work. In practice, I used a Matlab implementation to pre-generate all required images, and I did not really familiar with your mentioned open3d implementation. I will share all my code and data when the corresponding paper is formally accepted. For your question, I think you can try other implementations of the hidden point removal algorithm (which is easy to find).

**Comment by Zscozer** [comment]
Ok, thank you so much.
